- ansible.builtin.file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0775
    recurse: true
  become: true
  loop:
    - bin
    - Caskroom
    - Cellar
    - etc
    - Frameworks
    - Homebrew
    - include
    - lib
    - opt
    - sbin
    - share
    - var
- ansible.builtin.git:
    repo: 'https://github.com/Homebrew/brew'
    dest: '{{ homebrew_install }}'
    depth: 1
    update: false
  register: homebrew_git_result
- ansible.builtin.file:
    path: '{{ homebrew_prefix }}/bin/brew'
    src: '{{ homebrew_install }}/bin/brew'
    state: link
    force: true
  when: homebrew_prefix != homebrew_install
- ansible.builtin.shell:
    cmd: |
      {{ ('arch -arch ' + homebrew_arch) if homebrew_arch != ansible_machine }} \
        {{ homebrew_prefix }}/bin/brew update --force
  when: homebrew_git_result.before is none
- ansible.builtin.shell:
    cmd: |
      {{ ('arch -arch ' + homebrew_arch) if homebrew_arch != ansible_machine }} \
        {{ homebrew_prefix }}/bin/brew tap homebrew/core
  when: homebrew_git_result.before is none
