import = [
  "~/Config/alacritty/nord.toml",
]

[bell]
animation = "EaseOutSine"
duration = 100

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[cursor]
style = "Underline"
thickness = 0.2
unfocused_hollow = true

[font]
size = 14.0
builtin_box_drawing = true

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-li", "--no-global-rcs"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.85
blur = true

[window.padding]
x = 6
y = 3
