[bell]
animation = "EaseOutSine"
color = "#d8dee9"
duration = 100

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.bright]
black = "#77829c"
blue = "#9cb5ce"
cyan = "#8fbcbb"
green = "#b8cda5"
magenta = "#c4a6be"
red = "#cc8289"
white = "#eceff4"
yellow = "#ebe089"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#566176"
blue = "#5e81ac"
cyan = "#89afcd"
green = "#8da37b"
magenta = "#9d8098"
red = "#a35c68"
white = "#a8afbd"
yellow = "#dca493"

[colors.footer_bar]
background = "#2e333f"
foreground = "#88c0d0"

[colors.normal]
black = "#616e88"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#d8dee9"
yellow = "#ebcb8b"

[colors.primary]
background = "#323845"
bright_foreground = "#eceff4"
dim_foreground = "#a8afbd"
foreground = "#d8dee9"

[colors.search.focused_match]
background = "#4c5569"
foreground = "#9cb5ce"

[colors.search.matches]
background = "#819ab3"
foreground = "#3b4151"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
style = "Underline"
thickness = 0.2
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
opacity = 0.88

[window.padding]
x = 6
y = 3
