#!/bin/sh
# vim: ft=sh ts=2 sw=2 et:

# GNU ls
# TODO: Replace with third party LS_COLORS tool.
for b in \
  /usr/local/opt/coreutils/libexec/gnubin/dircolors    \
  /opt/homebrew/opt/coreutils/libexec/gnubin/dircolors \
  "$(command -v dircolors 2>/dev/null)"; do
  [ -x "$b" ] && eval "$("$b" -b "$CONF/dir_colors")"
done
unset b

# General
# https://bixense.com/clicolors/
export CLICOLOR=1

# Apps
export HIGHLIGHT_STYLE="nord"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --color=16,hl:6,hl+:14,fg:-1,\
fg+:11,bg:-1,bg+:-1,prompt:6,pointer:11,disabled:8,info:12,marker:3,\
spinner:13,header:12"
