#!/bin/sh
# vim: ft=sh ts=2 sw=2 et:

# Basic utils
export EDITOR="micro"
export GIT_EDITOR="$EDITOR"
export TERMINAL="alacritty"
export CLICOLOR=1
export LESSHISTFILE="-"
export PAGER="less"
if has bat; then
  export PAGER="bat"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

if [ -n "$GUI" ]; then
  # For the pedantic: I'm aware VISUAL should be set to a "visual mode" editor,
  # as opposed to a line-mode, ie, something like vi inside the terminal, not
  # necessarily a GUI app. But most tools have forgotten this convention by now
  # so I think it's useful to repurpose them for a more modern distinction.
  export VISUAL="code"
fi
