#!/bin/sh
# vim: ft=sh ts=2 sw=2 et:

# Basic utils
export EDITOR="micro"
export TERMINAL="alacritty"
export CLICOLOR=1
export LESSHISTFILE="-"
export PAGER="less"
if has bat; then
  export PAGER="bat"
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

if [ -n "$GUI" ]; then
  export GEDITOR="code"
fi
