#!/bin/sh

# Bluetooth stack bug intermittently prevents sleep, and causes mid-sleep wakeup
#"${HOME}"/bin/btdown >/dev/null 2>/dev/null &

# Lock the screen
#pgrep slock >/dev/null 2>/dev/null || slock &
xset s activate  # xss-lock service listens to this event

# Remember the backlight brightness
#xbacklight -get > "${XDG_DATA_HOME:-$HOME/.local/share}/brightness"

# Wait a brief while for Bluetooth to come down, and the screen to lock
#sleep 4
