- name: 'Configure Amethyst'
  hosts: 'localhost'
  vars:
    settings:
      - { key: 'enables-layout-hud',                 value: true,  domain: 'com.amethyst.Amethyst' }
      - { key: 'enables-layout-hud-on-space-change', value: false, domain: 'com.amethyst.Amethyst' }
      - { key: 'float-small-windows',                value: true,  domain: 'com.amethyst.Amethyst' }
      - { key: 'floating-is-blacklist',              value: true,  domain: 'com.amethyst.Amethyst' }
      - { key: 'focus-follows-mouse',                value: false, domain: 'com.amethyst.Amethyst' }
      - { key: 'follow-space-thrown-windows',        value: false, domain: 'com.amethyst.Amethyst' }
      - { key: 'ignore-menu-bar',                    value: false, domain: 'com.amethyst.Amethyst' }
      - { key: 'layouts',                            value: ['floating', 'widescreen-tall', 'column'], domain: 'com.amethyst.Amethyst' }
      - { key: 'mod1',                               value: ['option', 'shift'],                       domain: 'com.amethyst.Amethyst' }
      - { key: 'mod2',                               value: ['option', 'shift', 'control'],            domain: 'com.amethyst.Amethyst' }
      - { key: 'mouse-follows-focus',                value: false, domain: 'com.amethyst.Amethyst' }
      - { key: 'mouse-resizes-windows',              value: true,  domain: 'com.amethyst.Amethyst' }
      - { key: 'new-windows-to-main',                value: false, domain: 'com.amethyst.Amethyst' }
      - { key: 'restore-layouts-on-launch',          value: true,  domain: 'com.amethyst.Amethyst' }
      - { key: 'screen-padding-bottom',              value: 0,     domain: 'com.amethyst.Amethyst' }
      - { key: 'screen-padding-left',                value: 0,     domain: 'com.amethyst.Amethyst' }
      - { key: 'screen-padding-right',               value: 0,     domain: 'com.amethyst.Amethyst' }
      - { key: 'screen-padding-top',                 value: 0,     domain: 'com.amethyst.Amethyst' }
      - { key: 'smart-window-margins',               value: false, domain: 'com.amethyst.Amethyst' }
      - { key: 'window-margin-size',                 value: 28,    domain: 'com.amethyst.Amethyst' }
      - { key: 'window-margins',                     value: true,  domain: 'com.amethyst.Amethyst' }
    floating_apps:
      'com.1password.1password':              []
      'com.agilebits.onepassword7':           []
      'com.amethyst.Amethyst':                []
      'com.apple.ActivityMonitor':            []
      'com.apple.AppStore':                   []
      'com.apple.Automator':                  []
      'com.apple.backup.launcher':            []
      'com.apple.calculator':                 []
      'com.apple.DigitalColorMeter':          []
      'com.apple.FontBook':                   []
      'com.apple.installer':                  []
      'com.apple.Preview':                    []
      'com.apple.systempreferences':          []
      'com.daisydiskapp.DaisyDiskStandAlone': []
      'com.dmitrynikolaev.numi':              []
      'com.lujjjh.LinearMouse':               []
      'com.rogueamoeba.soundsource':          []
      'com.runningwithcrayons.Alfred':        []
      'com.titanium.OnyX':                    []
      'io.alacritty':                         ['Floatty']
      'net.freemacsoft.AppCleaner':           []
      'org.mozilla.firefox':                  ['Library']
      'org.mozilla.firefoxdeveloperedition':  ['Library']
  tasks:
    - ansible.builtin.command: killall Amethyst
      ignore_errors: true
    # Keybindings involve binary blobs, so we import from include/. This will
    # overwrite all other settings as well, so do it first, and then import 
    # other settings declaratively on top of it.
    - ansible.builtin.shell: |
        defaults import com.amethyst.Amethyst "{{ playbook_dir }}/../include/com.amethyst.Amethyst.plist"
    - include_role: 
        name: ../roles/macos-defaults
      loop: "{{ settings }}"
    - ansible.builtin.shell: |
        # NOTE: `defaults delete` seems to be broken on newer versions of
        # MacOS, never finding the domain, even if it exists. Write empty array 
        # instead.
        defaults write com.amethyst.Amethyst floating -array
    - ansible.builtin.shell: |
        defaults write com.amethyst.Amethyst floating -array-add '
          <dict>
            <key>id</key>
            <string>{{ item.key }}</string>
            <key>window-titles</key>
            <array>
              {% for window_title in item.value %}
              <string>{{ window_title }}</string>
              {% endfor %}
            </array>
          </dict>'
      loop: "{{ floating_apps | dict2items }}"
