- name: 'Configure Keycastr'
  hosts: 'localhost'
  vars:
    settings:
      - { key: 'SFAppDarkThemeName',           value: 'Nord',           domain: 'net.shinyfrog.bear' }
      - { key: 'SFAppIconMatchesTheme',        value: 1,                domain: 'net.shinyfrog.bear' }
      - { key: 'SFEditorFontSize',             value: 16,               domain: 'net.shinyfrog.bear' }
      - { key: 'SFEditorLineHeightMultiplier', value: 1.4,              domain: 'net.shinyfrog.bear' }
      - { key: 'SFEditorLineWidthMultiplier',  value: 55,               domain: 'net.shinyfrog.bear' }
      - { key: 'SFFontThemeName',              value: 'Helvetica Neue', domain: 'net.shinyfrog.bear' }
  tasks:
    - include_role: 
        name: ../roles/macos-defaults
      loop: "{{ settings }}"
