- name: 'Configure Keycastr'
  hosts: 'localhost'
  vars:
    settings:
      - { key: 'AllowClipboardAccess',      value: 1,                          domain: 'com.googlecode.iterm2' }
      - { key: 'CopySelection',             value: 0,                          domain: 'com.googlecode.iterm2' }
      - { key: 'HideScrollbar',             value: 1,                          domain: 'com.googlecode.iterm2' }
      - { key: 'HideTabNumber',             value: 1,                          domain: 'com.googlecode.iterm2' }
      - { key: 'LoadPrefsFromCustomFolder', value: 1,                          domain: 'com.googlecode.iterm2' }
      - { key: 'PrefsCustomFolder',         value: '/Users/ant/Config/iterm2', domain: 'com.googlecode.iterm2' }
      - { key: 'PromptOnQuit',              value: 0,                          domain: 'com.googlecode.iterm2' }
      - { key: 'QuitWhenAllWindowsClosed',  value: 1,                          domain: 'com.googlecode.iterm2' }
      - { key: 'SUEnableAutomaticChecks',   value: 1,                          domain: 'com.googlecode.iterm2' }
      - { key: 'dispUseBorderlayIcon',      value: 0,                          domain: 'com.googlecode.iterm2' }
  tasks:
    - include_role: 
        name: ../roles/macos-defaults
      loop: "{{ settings }}"
