- name: 'Configure Keycastr'
  hosts: 'localhost'
  vars:
    settings:
      - { key: 'SUAutomaticallyUpdate', value: 1,   domain: 'com.dmitrynikolaev.numi' }
      - { key: 'SUEnableAutomaticChecks', value: 1, domain: 'com.dmitrynikolaev.numi' }
      - { key: 'activationOnUpdate', value: 1,      domain: 'com.dmitrynikolaev.numi' }
      - { key: 'alfredIntegration', value: 1,       domain: 'com.dmitrynikolaev.numi' }
      - { key: 'alwaysOnTop', value: 1,             domain: 'com.dmitrynikolaev.numi' }
      - { key: 'correctFinish', value: 1,           domain: 'com.dmitrynikolaev.numi' }
      - { key: 'menuBarMode', value: 1,             domain: 'com.dmitrynikolaev.numi' }
  tasks:
    - include_role: 
        name: ../roles/macos-defaults
      loop: "{{ settings }}"
