- name: 'Enable autostart items'
  hosts: 'localhost'
  vars:
    settings:
      # appname          start hidden?
      '1Password 7':     true
      'Amethyst':        false
      'BetterTouchTool': false
      'Hammerspoon':     false
      'LinearMouse':     false
      'SoundSource':     false
  tasks:
    - ansible.builtin.shell: |
        appname="{{ item.key }}"
        hidden="{{ item.value }}"
        {% raw %}
        if [ ! -e "/Applications/$appname ]; then
          exit 1
        fi
        case val in "$hidden"
          true)  ;;
          false) ;;
          *) exit 1 ;;
        esac
        osascript -e '
          set appname to "'"$appname"'"
          set hidden to '"$hidden"'
          tell application "System Events"
            set loginitems to the name of every login item
            if loginitems contains appname then
              tell application "System Events" to delete login item appname
            end if
            tell application "System Events" to make login item at end with properties { name: appname, path: "/Applications/" & appname & ".app", hidden: hidden }
          end tell
        {% endraw %}'
      loop: "{{ login_items | dict2items }}"
