# There's no good CLI-native interface for this. We could try and interact with 
# the backing store directly, but it's changed several times over the past few 
# years. On the other hand, interacting with System Events has been pretty 
# stable. I don't love writing AppleScript, but it works.
- name: 'Enable autostart items'
  hosts: 'localhost'
  vars:
    login_items:
      # appname          start hidden?
      '1Password 7':     true
      'Amethyst':        false
      'BetterTouchTool': false
      'Hammerspoon':     false
      'LinearMouse':     false
      'SoundSource':     false
  tasks:
    - ansible.builtin.shell: |
        appname="{{ item.key }}"
        apphidden="{{ item.value | lower }}"
        {% raw %}
        if [ ! -e "/Applications/$appname.app" ]; then
          exit 0
        fi
        case "$apphidden" in
          true)  ;;
          false) ;;
          *) exit 1 ;;
        esac
        osascript <<-EOF
          set appname to "$appname"
          tell application "System Events"
            set loginitems to the name of every login item
            if loginitems contains appname then
              delete login item appname
            end if
            make login item at end with properties { name: appname, path: "/Applications/" & appname & ".app", hidden: $apphidden }
          end tell
        EOF
        {% endraw %}
      loop: "{{ login_items | dict2items }}"
