- name: 'Setup Homebrew taps'
  hosts: 'localhost'
  tasks:
    - community.general.homebrew_tap:
        tap:
          - homebrew/cask
          - homebrew/cask-fonts
          - homebrew/cask-versions  # Firefox update channels
    - community.general.homebrew:
        update_homebrew: yes
