- name: 'Install Homebrew formulae'
  hosts: 'localhost'
  vars:
    formulae: 
      - ansible
      - atool
      - aws-vault
      - aws-sam-cli
      - awscli
      - bash
      - bat
      - chamber
      - circleci
      - clac
      - coreutils
      - dash
      - exa
      - exiftool
      - fd
      - ffmpeg
      - ffmpegthumbnailer
      - fswatch
      - fzf
      - gawk
      - gh
      - git
      - gnu-sed
      - go
      - gopls
      - graphicsmagick
      - grep
      - hexyl
      - highlight
      - jd
      - jq
      - k3d
      - kubernetes-cli
      - luarocks
      - magic-wormhole
      - mas
      - media-info
      - micro
      - moreutils
      - mosh
      - odt2txt
      - p7zip
      - packer
      - pandoc
      - pastel
      - postgresql
      - pv
      - pwgen
      - ranger
      - ripgrep-all
      - rsync
      - visidata
      - shellcheck
      - sqlite3
      - telnet
      - terraform
      - w3m
      - watch
      - wget
  tasks:
    - community.general.homebrew:
        formula: "{{ formulae }}"
        # Default 'path' picks up Intel brew when both are installed on M1
        path: "{{ {'arm64': '/opt/homebrew/bin', 'x86_64': '/usr/local/bin'}[ansible_architecture] }}"
