- name: 'Install Homebrew formulae'
  hosts: 'localhost'
  tasks:
    - community.general.homebrew:
        formula:
          - ansible
          - atool
          - awscli
          - bash
          - bat
          - circleci
          - clac
          - coreutils
          - dash
          - exa
          - exiftool
          - fd
          - ffmpeg
          - ffmpegthumbnailer
          - fswatch
          - fzf
          - gawk
          - gh
          - git
          - gnu-sed
          - go
          - gopls
          - graphicsmagick
          - grep
          - hexyl
          - highlight
          - jd
          - jq
          - luarocks
          - magic-wormhole
          - mas
          - media-info
          - micro
          - moreutils
          - mosh
          - odt2txt
          - p7zip
          - pandoc
          - pastel
          - pv
          - pwgen
          - ranger
          - ripgrep-all
          - rsync
          - shellcheck
          - skhd
          - sqlite3
          - telnet
          - terraform
          - tig
          - w3m
          - watch
          - wget
          - yabai
