# NOTE: Requires `mas`, installed in 21-install-formulae.yml
# NOTE: Assumes AppStore is logged in
- name: 'Install AppStore apps'
  hosts: 'localhost'
  vars:
    apps:
      - 539883307  # LINE
      - 1475387142 # Tailscale
  tasks:
    - community.general.mas:
        id: "{{ apps }}"
      ignore_errors: true
