- name: 'Install Homebrew casks'
  hosts: 'localhost'
  vars:
    casks:
      - 1password
      - alacritty
      - amethyst
      - appcleaner
      - bettertouchtool
      - firefox-developer-edition
      - daisydisk
      - discord
      - font-iosevka
      - font-iosevka-aile
      - font-iosevka-etoile
      - hammerspoon
      - istat-menus
      - keycastr
      - linearmouse
      - onyx
      - rar
      - secretive
      - session-manager-plugin
      - soundsource
      - spotify
      - textual
      - the-unarchiver
      - tunnelblick
      - visual-studio-code
      - vivaldi
  tasks:
    - community.general.homebrew_cask:
        cask: "{{ casks }}"
        install_options: no-quarantine
        # Default 'path' picks up Intel brew when both are installed on M1
        path: "{{ {'arm64': '/opt/homebrew/bin', 'x86_64': '/usr/local/bin'}[ansible_architecture] }}"
        sudo_password: "{{ ansible_become_password }}"
