- name: 'Install Homebrew casks'
  hosts: 'localhost'
  tasks:
    - community.general.homebrew_cask:
        cask:
          - 1password
          - alacritty
          - alfred4
          - app-tamer
          - appcleaner
          - cleanshot
          - daisydisk
          - discord
          - font-iosevka
          - font-iosevka-aile
          - font-iosevka-etoile
          - iina
          - iterm2
          - karabiner-elements
          - keycastr
          - linearmouse
          - maccy
          - mullvadvpn
          - onyx
          - orbstack
          - rar
          - secretive
          - slack
          - spaceid
          - switchresx
          - the-unarchiver
          - visual-studio-code
          - vivaldi
        install_options: 'no-quarantine,force'
        sudo_password: "{{ ansible_become_password }}"
