- name: 'Install Homebrew casks'
  hosts: 'localhost'
  tasks:
    - community.general.homebrew_cask:
        cask:
          - 1password
          - alacritty
          - amethyst
          - appcleaner
          - bettertouchtool
          - daisydisk
          - font-iosevka
          - font-iosevka-aile
          - font-iosevka-etoile
          - iterm2
          - keycastr
          - linearmouse
          - onyx
          - rar
          - secretive
          - spotify
          - the-unarchiver
          - visual-studio-code
          - vivaldi
        install_options: 'no-quarantine,force'
        sudo_password: "{{ ansible_become_password }}"
