# NOTE: Requires `mas`, installed in 11-install-formulae.yml
# NOTE: Assumes AppStore is logged in
- name: 'Install AppStore apps'
  hosts: 'localhost'
  tasks:
    - community.general.mas:
        id:
          - 1091189122  # Bear
          - 539883307   # LINE
      # Skip errors because we never log into AppStore on work machines
      ignore_errors: true
