- name: 'Setup home symlinks'
  hosts: 'localhost'
  vars:
    home_symlinks:
      # - set `target` for link target absolute path
      # - set `config` for link target relative to Config/
      # - set neither for link target relative to Config/, taken as linkname 
      #   with  first `.` removed (if present)
      - { linkname: '.aws' }
      - { linkname: '.config',             target: 'Config' }
      - { linkname: '.docker' }
      - { linkname: '.gitconfig',          config: 'git/config' }
      - { linkname: '.kube' }
      - { linkname: '.ssh',                target: 'Security/ssh' }
      - { linkname: '.terraform.d',        config: 'terraform/terraform.d' }
      - { linkname: '.terraformrc',        config: 'terraform/rc' }
      - { linkname: '.vscode' }
      - { linkname: '.zshenv',             config: 'zsh/env' }
      - { linkname: '.zshrc',              config: 'zsh/rc' }
      - { linkname: 'Bin',                 config: 'bin' }
      - { linkname: 'Security/ssh/config', config: 'ssh/config' }
  tasks:
    - ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/{{ item.linkname }}"
        src: "{{ item.target if 'target' in item else 'Config/' + item.config | default(item.linkname | regex_replace('^\\.')) }}"
        state: link
        force: true
      loop: "{{ home_symlinks }}"
