# NOTE: On new machine setup, we're likely running these Ansible playbooks from
# a tarballed copy of the dotfiles, so make sure it's cloned locally.
- name: 'Clone dotfiles'
  hosts: 'localhost'
  tasks:
    # Do the initial clone over HTTPS since we're probably not set up for SSH
    # authentication locally, yet.
    - ansible.builtin.git:
        repo: 'https://github.com/aeadio/dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/Config"
        remote: 'github-https'
        update: false
    # .. but make sure the usual origin is available for later.
    - ansible.builtin.git:
        repo: 'git@github.com:aeadio/dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/Config"
        remote: 'origin'
        update: false
