#!/usr/bin/env bash

. blocks/common

buttons=('' '' '' 'xbacklight -inc 5' 'xbacklight -dec 5')

label=f26c

render() {
  printf '%s\n' "$(icon $label) $(xbacklight -get)%"
}

listen <(inotifywait -qme modify --format '' /sys/class/backlight/intel_backlight/brightness)
