#!/usr/bin/env bash

. blocks/common

label=f2c9
warn_threshold_mid=85
warn_threshold_high=95

maxtemp() {
  local maxtemp="$(sysfs_max /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_input)"
  printf '%s' "$((maxtemp / 1000))"
}

render() {
  local temp="$(maxtemp)"
  local color
  
  if (( $temp >= $warn_threshold_high )); then
    color=bad
  elif (( $temp >= $warn_threshold_mid )); then
    color=warn
  fi
  
  printf '%s\n' "$(icon $label) $(color $color "$temp°C")"
}

repeat
