#!/usr/bin/env bash

. blocks/common

buttons=("terminal -f sh -c 'doas system-update -vo; pause' #c")

label=f0aa

get_num_updates() {
  xbps-install -un | wc -l
}

render() {
  local updates="$(get_num_updates)"
  if [[ $updates > 0 ]]; then
    printf '%s\n' "$(icon $label) $(color green "$updates")"
  else
    printf '%s\n' ''
  fi
}

repeat 300
