#!/usr/bin/env bash

. blocks/common

declare -A labels
labels[connected]=f132
labels[disconnected]=f09c

render() {
	local vpn="$(retry 5 getvpn)"
  local label color
  
  if [[ -z $vpn ]]; then label=disconnected; color=dim; vpn=none
  else                   label=connected;    color=ok
  fi
  
  printf '%s\n' "$(icon ${labels[$label]}) $(color $color "$vpn")"
}

# If invoked immediately upon login, `ip monitor` is exhibiting extremely high
# rates of events indefinitely, even if restarting the block would cause it to
# cool down to a more reasonable level. For now, just delay starting up the
# event listening. TODO: figure out wtf is going on.
sleep 2

listen <(ip monitor)
