#!/usr/bin/env zsh

config=(
  # Tiling
  layout                      bsp
  
  # Window behavior
  window_origin_display       focused
  window_placement            second_child
  #window_topmost             on      # SA
  auto_balance                off
  split_type                  auto
  split_ratio                 0.70
  
  # Input behavior
  mouse_follows_focus         off
  focus_follows_mouse         off
  
  mouse_drop_action           swap
  
  mouse_modifier              cmd
  mouse_action1               move
  mouse_action2               resize
  
  # Appearance
  top_padding                 28
  bottom_padding              28
  left_padding                28
  right_padding               28
  window_gap                  28
  
  window_opacity              on      # SA
  active_window_opacity       1.0     # SA
  normal_window_opacity       0.92    # SA
  window_opacity_duration     0.1     # SA
  
  window_animation_duration   0       # SA
  
  window_shadow               on      # SA
  
  window_border               off
  window_border_width         1
  window_border_radius        9
  window_border_blur          off
  active_window_border_color  '0x00000000'
  normal_window_border_color  '0x00000000'
  insert_feedback_color       '0xaa8fbcbb'
)

typeset -A rules=(
  # System dialogues
  ['^Activity Monitor$']=
  ['^App Store$']=
  ['^Archive Utility$']=
  ['^Automator$']=
  ['^Boot Camp Assistant$']=
  ['^Contacts$']=
  ['^Calculator$']=
  ['^ColorSync Utility$']=
  ['^Dictionary$']=
  ['^Digital Color Meter$']=
  ['^Disk Utility$']=
  ['^FaceTime$']=
  ['^Finder$']='(Co(py|nnect)|Move|Info|Pref)'
  ['^Font Book$']=
  ['^Installer$']=
  ['^Migration Assistant$']=
  ['^Preview$']=
  ['^Safari$']='^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$'
  ['^Script Editor$']=
  ['^Shortcuts$']=
  ['^Software Update$']=
  ['^System Information$']=
  ['^System (Preferences|Settings)$']=
  ['^Time Machine$']=
  ['^VoiceMemos$']=
  
  # Apps
  ['^1Password']=
  ['^Alfred']=
  ['^AppCleaner$']=
  ['^AppTamer$']=
  ['^AWS VPN Client$']=
  ['^Battle.net$']=
  ['^CleanShot']=
  ['^DaisyDisk$']=
  ['^Firefox']='^Library$'
  ['^Google Drive$']=
  ['^Karabiner']=
  ['^KeyCastr$']=
  ['^LinearMouse$']=
  ['^Little Snitch']=
  ['^NordVPN$']=
  ['^Numi$']=
  ['^OnyX$']=
  ['^Secretive$']=
  ['^Steam$']=
  ['^The Unarchiver$']=
  ['^zoom.us$']=
)

# Load scripting additions (SA)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Load config
yabai -m config $config

for app in ${(k)rules};
  yabai -m rule --add app=$app ${rules[$app]:+--title=$rules[$app]} manage=off
