#!/usr/bin/env zsh

() {
  local padding=28
  
  # Load SA
  yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
  sudo yabai --load-sa
  
  # Tiling
  yabai -m config layout                      bsp
  
  # Window behavior
  yabai -m config window_origin_display       focused
  yabai -m config window_placement            second_child
# yabai -m config window_topmost              on      # SA
  yabai -m config auto_balance                off
  yabai -m config split_type                  auto
  yabai -m config split_ratio                 0.70
  
  # Input behavior
  yabai -m config mouse_follows_focus         off
  yabai -m config focus_follows_mouse         off
  
  yabai -m config mouse_drop_action           swap
  
  yabai -m config mouse_modifier              cmd
  yabai -m config mouse_action1               move
  yabai -m config mouse_action2               resize
  
  # Appearance
  yabai -m config top_padding                 $padding
  yabai -m config bottom_padding              $padding
  yabai -m config left_padding                $padding
  yabai -m config right_padding               $padding
  yabai -m config window_gap                  $padding
  
  yabai -m config window_opacity              off     # SA
  yabai -m config active_window_opacity       1.0     # SA
  yabai -m config normal_window_opacity       0.92    # SA
  yabai -m config window_opacity_duration     0.1     # SA
  
  yabai -m config window_animation_duration   0.08    # SA
  
  yabai -m config window_shadow               on      # SA
  
  yabai -m config window_border               off
  yabai -m config window_border_width         1
  yabai -m config window_border_radius        9
  yabai -m config window_border_blur          off
  yabai -m config active_window_border_color  ''
  yabai -m config normal_window_border_color  ''
  yabai -m config insert_feedback_color       '0xaa8fbcbb'
  
  # Rules
  # System dialogues
  yabai -m rule --add app="^Activity Monitor$"    manage=off
  yabai -m rule --add app="^App Store$"           manage=off
  yabai -m rule --add app="^Archive Utility$"     manage=off
  yabai -m rule --add app="^Automator$"           manage=off
  yabai -m rule --add app="^Boot Camp Assistant$" manage=off
  yabai -m rule --add app="^Contacts$"            manage=off
  yabai -m rule --add app="^Calculator$"          manage=off
  yabai -m rule --add app="^ColorSync Utility$"   manage=off
  yabai -m rule --add app="^Dictionary$"          manage=off
  yabai -m rule --add app="^Digital Color Meter$" manage=off
  yabai -m rule --add app="^Disk Utility$"        manage=off
  yabai -m rule --add app="^FaceTime$"            manage=off
  yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
  yabai -m rule --add app="^Font Book$"           manage=off
  yabai -m rule --add app="^Installer$"           manage=off
  yabai -m rule --add app="^Migration Assistant$" manage=off
  yabai -m rule --add app="^Preview$"             manage=off
  yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
  yabai -m rule --add app="^Script Editor$"       manage=off
  yabai -m rule --add app="^Shortcuts$"           manage=off
  yabai -m rule --add app="^Software Update$"     manage=off
  yabai -m rule --add app="^System Information$"  manage=off
  yabai -m rule --add app="^System (Preferences|Settings)$" manage=off
  yabai -m rule --add app="^Time Machine$"        manage=off
  yabai -m rule --add app="^VoiceMemos$"          manage=off
  
  # Apps
  yabai -m rule --add app="^1Password"            manage=off
  yabai -m rule --add app="^Alfred"               manage=off
  yabai -m rule --add app="^AppCleaner$"          manage=off
  yabai -m rule --add app="^AppTamer$"            manage=off
  yabai -m rule --add app="^AWS VPN Client$"      manage=off
  yabai -m rule --add app="^CleanShot"            manage=off
  yabai -m rule --add app="^DaisyDisk$"           manage=off
  yabai -m rule --add app="^Firefox" title="^Library$" manage=off
  yabai -m rule --add app="^Google Drive$"        manage=off
  yabai -m rule --add app="^Karabiner"            manage=off
  yabai -m rule --add app="^KeyCastr$"            manage=off
  yabai -m rule --add app="^LinearMouse$"         manage=off
  yabai -m rule --add app="^Little Snitch"        manage=off
  yabai -m rule --add app="^NordVPN$"             manage=off
  yabai -m rule --add app="^Numi$"                manage=off
  yabai -m rule --add app="^OnyX$"                manage=off
  yabai -m rule --add app="^Secretive$"           manage=off
  yabai -m rule --add app="^Steam$"               manage=off
  yabai -m rule --add app="^The Unarchiver$"      manage=off
  yabai -m rule --add app="^zoom.us$"             manage=off
}
