- name: 'Configure dock'
  hosts: 'localhost'
  tasks:
    - ansible.builtin.command: |
        defaults import com.apple.dock "{{ playbook_dir }}/../include/com.apple.dock.plist"
    - ansible.builtin.command: |
        killall Dock
      ignore_errors: true
