- name: 'Configure dock'
  hosts: 'localhost'
  tasks:
    - ansible.builtin.command: |
        defaults import com.apple.dock "{{ playbook_dir }}/../include/com.apple.dock.plist"
    # The Dock is pretty eager to overwrite plist values, so we're currently
    # racing it. Kill as soon as we can.
    - ansible.builtin.command: |
        killall Dock
      ignore_errors: true
