# BUG: Inserting just the TCIM IMEs breaks the IME settings completely
- name: 'Enable TCIM IMEs'
  hosts: 'localhost'
  vars:
    imes:
      - Pinyin
      - Zhuyin
  tasks:
    - ansible.builtin.shell:
        executable: /bin/zsh
        cmd: |
          ime='{{ item }}'
          {% raw %}
          domain='com.apple.HIToolbox'
          key='AppleEnabledInputSources'
          
          if [[ $(defaults read $domain $key) =~ $ime ]] exit 0
          
          defaults write $domain $key -array-add '
            <dict>
              <key>Bundle ID</key>
              <string>com.apple.inputmethod.TCIM</string>
              <key>Input Mode</key>
              <string>com.apple.inputmethod.TCIM.'"$ime"'</string>
              <key>InputSourceKind</key>
              <string>Input Mode</string>
            </dict>'
          
          if (( $? )) exit 2
          
          exit 1
          {% endraw %}
      register: result
      changed_when: result.rc == 1
      failed_when:  result.rc == 2
      loop: "{{ imes }}"
