- name: 'Configure MacOS input methods'
  hosts: 'localhost'
  tasks:
    - ansible.builtin.command: |
        defaults import com.apple.HIToolbox "{{ playbook_dir }}/../include/com.apple.HIToolbox.plist"
