# This configures Night Shift, which is a bit unusual -- it's apparently run 
# as root, and configured by a plist in root's Library, even though the 
# configuration is user-specific. Moreover, the settings are keyed by the 
# user's dscl GUID.
- name: 'Configure screen color'
  hosts: 'localhost'
  become: true
  vars:
    cb_settings: |
      {
        CBBlueReductionStatus = {
          AutoBlueReductionEnabled = 1;
          BlueLightReductionDisableScheduleAlertCounter = 3;
          BlueLightReductionSchedule = {
            DayStartHour = 7;
            DayStartMinute = 0;
            NightStartHour = 22;
            NightStartMinute = 0;
          };
          BlueReductionMode = 1;
          BlueReductionSunScheduleAllowed = 1;
          Version = 1;
        };
        CBColorAdaptationEnabled = 1;
      }
  tasks:
    - ansible.builtin.shell:
        executable: /bin/zsh
        cmd: |
          user='{{ ansible_user_id }}'
          cb_settings='{{ cb_settings }}'
          {% raw %}
          domain='/var/root/Library/Preferences/com.apple.CoreBrightness.plist'
          
          userpath=$(eval print "~$user")
          if [[ ! -d $userpath ]] exit 2
          
          dscl . -read $userpath GeneratedUID |
            sed 's/GeneratedUID: //' |
            read -r useruid
          if [[ -z $useruid ]] exit 2
          
          cbkey="CBUser-$useruid"
          
          [[ $(defaults read $domain $cbkey) =~ "BlueReductionEnabled = 1" ]] &&
            exit 0
          
          defaults write $domain $cbkey "$cb_settings" ||
            exit 2
          
          exit 1
          {% endraw %}
      register: result
      changed_when: result.rc == 1
      failed_when:  result.rc == 2
