#!/bin/sh

#"$HOME"/bin/setscreenblank
SVDIR="$HOME"/sv sv restart wallpaper

# Ask i3 to reload its config since it picks up workspace->screen assignment 
# from active autorandr profile name.
#i3-msg reload
