# osx_defaults cowardly errors if there's a type mismatch, which is pretty 
# common among MacOS defaults, which are weakly typed. There's no flag to
# suppress this. Try to catch this failure, delete, and rerun.
- block:
    - community.general.osx_defaults:
        key:    "{{ item.key }}"
        value:  "{{ item.value }}"
        domain: "{{ item.domain | default('NSGlobalDomain') }}"
        type: |-
          {{
            {
              'list': 'array',
              'AnsibleUnicode': 'string',
              'AnsibleUnsafeText': 'string'
            }[(item.value | type_debug)] | default(item.value | type_debug)
          }}
  rescue:
    - community.general.osx_defaults:
        key:    "{{ item.key }}"
        domain: "{{ item.domain | default('NSGlobalDomain') }}"
        state:  "absent"
      when: ansible_failed_result is search("Type mismatch")
    - community.general.osx_defaults:
        key:    "{{ item.key }}"
        value:  "{{ item.value }}"
        domain: "{{ item.domain | default('NSGlobalDomain') }}"
        type: |-
          {{
            {
              'list': 'array',
              'AnsibleUnicode': 'string',
              'AnsibleUnsafeText': 'string'
            }[(item.value | type_debug)] | default(item.value | type_debug)
          }}
      when: ansible_failed_result is search("Type mismatch")
