#!/usr/bin/env zsh
# vim: ft=sh ts=2 sw=2 et:

# Some utility functions we'll use throughout rc.d and first party plugins.
quiet() {
  # If we're not connected to a terminal, then don't suppress stdout -- so that
  # quiet can be used inside pipelines without wrapping the whole thing.
  if [[ -t 1 ]]; then
    "$@" &>/dev/null
  else
    "$@" 2>/dev/null
  fi
}

has() {
  (( $+commands[$1] ))
}

isgnu() {
  has $1 && [[ $(quiet $1 --version) == *GNU* ]]
}
