#!/usr/bin/env zsh
# vim: ft=sh ts=2 sw=2 et:

autoload -Uz compinit &&
compinit

# Use menu selection
zstyle ':completion:*' menu select
LISTMAX=-1            # And don't prompt for "do you wish to see all N?"
setopt menu_complete  # And start menu selection immediately

# Use LS_COLORS for completion items
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Describe command lime parameters if recognized
zstyle ':completion:*' verbose true
zstyle ':completion:*' list-separator '#'

# List directories first
zstyle ':completion:*' list-dirs-first true

# Don't insert tab when there's no completions
zstyle ':completion:*' insert-tab false

# Case insensitive path-completion
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'

# Approximate completions, depending on input length
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle -e ':completion:*:approximate:*' \
  max-errors 'reply=($((($#PREFIX+$#SUFFIX)/4))numeric)'

# Ignore functions not intended to be user-facing
zstyle ':completion:*:functions' ignored-patterns \
  '((_|→|-|.)*|pre(cmd|exec)|chpwd|periodic|zsh(addhistory|exit))'

# Don't complete pwd during a 'cd ../'
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# Don't sort refs with 'git checkout'
zstyle ':completion:*:git-checkout:*' sort false

# Autosuggestion plugin
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
