#!/usr/bin/env zsh
# vim: ft=sh ts=2 sw=2 et:

autoload -Uz compinit &&
compinit

# Case insensitive path-completion
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'

# Approximate completions
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle -e ':completion:*:approximate:*' \
  max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3))numeric)'

# Ignore completion functions for commands you don't have:
zstyle ':completion:*:functions' ignored-patterns '_*'

# Don't complete version control files
zstyle ':completion:*:(all-|)files' ignored-patterns '(|*/)CVS'
zstyle ':completion:*:cd:*' ignored-patterns '(*/)#CVS'

# Don't complete pwd during a 'cd ../'
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# Autosuggestion plugin
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
