- name: 'Setup home directories'
  hosts: localhost
  connection: local
  vars:
    home_directories:
      - { dirname: 'Pictures/Screenshots' }
      - { dirname: 'Pictures/Wallpapers' }
      - { dirname: 'Security',     mode: 700 }
      - { dirname: 'Security/ssh', mode: 700 }
      - { dirname: 'Source' }
      - { dirname: 'Temp' }
  tasks:
    - ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/{{ item.dirname }}"
        mode: "{{ item.mode | default('0755') }}"
        state: directory
      loop: "{{ home_directories }}"
