#!run
# TODO: Enable autostart
- name: 'Configure LinearMouse'
  hosts: 'localhost'
  vars:
    amethyst_settings:
  tasks:
    - include_role: 
        name: roles/macos-defaults
      loop:
        - { key: 'linearMovementOn',                   value: true,      domain: 'com.lujjjh.LinearMouse' }
        - { key: 'linearScrollingOn',                  value: true,      domain: 'com.lujjjh.LinearMouse' }
        - { key: 'reverseScrollingOn',                 value: true,      domain: 'com.lujjjh.LinearMouse' }
        - { key: 'universalBackForwardOn',             value: true,      domain: 'com.lujjjh.LinearMouse' }
